// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLPXE5yl8sQtFgmlLf3Z8avVbFYNvjSSk',
    appId: '1:421634876367:web:f2909c4d17abdb279ba8ba',
    messagingSenderId: '421634876367',
    projectId: 'outfit-1aa79',
    authDomain: 'outfit-1aa79.firebaseapp.com',
    storageBucket: 'outfit-1aa79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFPfricF_6FQyEer1Ct8vf2eolj41Uns',
    appId: '1:421634876367:android:0adf85fef13132979ba8ba',
    messagingSenderId: '421634876367',
    projectId: 'outfit-1aa79',
    storageBucket: 'outfit-1aa79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCypZZ8Cz0hapqQrFJ0hppMj518mMaSnuM',
    appId: '1:421634876367:ios:d943bfb16df266c09ba8ba',
    messagingSenderId: '421634876367',
    projectId: 'outfit-1aa79',
    storageBucket: 'outfit-1aa79.firebasestorage.app',
    iosBundleId: 'com.example.outFitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCypZZ8Cz0hapqQrFJ0hppMj518mMaSnuM',
    appId: '1:421634876367:ios:d943bfb16df266c09ba8ba',
    messagingSenderId: '421634876367',
    projectId: 'outfit-1aa79',
    storageBucket: 'outfit-1aa79.firebasestorage.app',
    iosBundleId: 'com.example.outFitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLPXE5yl8sQtFgmlLf3Z8avVbFYNvjSSk',
    appId: '1:421634876367:web:5f14655ed4942eed9ba8ba',
    messagingSenderId: '421634876367',
    projectId: 'outfit-1aa79',
    authDomain: 'outfit-1aa79.firebaseapp.com',
    storageBucket: 'outfit-1aa79.firebasestorage.app',
  );
}
